### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by rainyBJ** [NaelF/BinaryCoP#1]
Very impressive work, wonder if you are going to release the training code related to this work?

**Comment by NaelF** [comment]
Thanks! We wanted to avoid redundant code as the training is done with Brevitas finn examples ([LINK](https://github.com/Xilinx/brevitas/tree/master/src/brevitas_examples/bnn_pynq)), and the dataset is the publicly available MaskedFace-Net ([LINK](https://github.com/cabani/MaskedFace-Net)). You can use these out of the box to achieve the same reported accuracies.
The MaskTheFace tool can be used to create more masked examples ([LINK](https://github.com/aqeelanwar/MaskTheFace)).
